### ISSUE TITLE
3-1

### ISSUE THREAD

**Issue by alfiezy** [Ice-Storm/structure-and-interpretation-of-blockchain#1]
Dear QYuan,

topic 3-1， line 49:  考虑交易背后中的示例，交易的输出是 vin 数组:

Should it be '考虑交易背后中的示例，交易的**输入**是 vin 数组' ?

Best,
Alfie

**Comment by Ice-Storm** [comment]
> Dear QYuan,
> 
> topic 3-1， line 49: 考虑交易背后中的示例，交易的输出是 vin 数组:
> 
> Should it be '考虑交易背后中的示例，交易的**输入**是 vin 数组' ?
> 
> Best,
> Alfie

**Comment by Ice-Storm** [comment]
非常感谢~已更正 @alfiezy
