### ISSUE TITLE
raft 共识

### ISSUE THREAD

**Issue by panos-xyz** [Ice-Storm/structure-and-interpretation-of-blockchain#2]
服务器故障的时间必须比消息交换的时间长，否则每当一个节点要收集到足够多选票的时候就宕机了，新一轮的投票又重复这个过程，导致足够的时间选出领导人。

这里应该是： 没有足够的时间选出领导人

**Comment by panos-xyz** [comment]
广播的**世界**必须小于选举超时时间一个数量级，这样领导者才能发送稳定的心跳阻止跟随者进入候选人状态。

广播的时间

**Comment by Ice-Storm** [comment]
> 服务器故障的时间必须比消息交换的时间长，否则每当一个节点要收集到足够多选票的时候就宕机了，新一轮的投票又重复这个过程，导致足够的时间选出领导人。
> 
> 这里应该是： 没有足够的时间选出领导人

ok，已经修改
